POST http://localhost:80/api/item
Content-Type: application/json

{}

###
POST  http://localhost:3000/api/auth/register
Content-Type: "application/json"

{
    "username" : "admin",
    "password": "12345678",
    "email": "admin@localhost.com",
    "lastname": "admin",
    "firstname": "admin"
}
###

POST  http://localhost:3000/api/auth/login
Content-Type: "application/json"

{
   "username" : "admin",
    "password": "12345678",
}